---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	detect_emergency(detect_emergency)
	retrieve_knowledge(retrieve_knowledge)
	invoke_tools(invoke_tools)
	format_knowledge(format_knowledge)
	build_messages(build_messages)
	llm_invoke(llm_invoke)
	decide_continue(decide_continue)
	incr_followup(incr_followup)
	__end__([<p>__end__</p>]):::last
	__start__ --> detect_emergency;
	build_messages --> llm_invoke;
	decide_continue -. &nbsp;end&nbsp; .-> __end__;
	decide_continue -. &nbsp;followup&nbsp; .-> incr_followup;
	detect_emergency --> retrieve_knowledge;
	format_knowledge --> build_messages;
	incr_followup --> build_messages;
	invoke_tools --> format_knowledge;
	llm_invoke --> decide_continue;
	retrieve_knowledge --> invoke_tools;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
